task-manager/web/task_manager/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from . import views

app_name = "task_manager"

users_patterns = [
    url(r'^$', views.users, name='users'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'task_manager:home'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
]

categories_patterns = [
    url(r'^$', views.categories, name='categories'),
    url(r'^new/$', views.create_category, name='new_category'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_category, name='edit_category'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_category, name='delete_category'),
]

tasks_patterns = [
    url(r'^$', views.tasks, name='tasks'),
    url(r'^new/$', views.create_task, name='new_task'),
    url(r'^(?P<id>[0-9]+)/$', views.show_task, name='show_task'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_task, name='edit_task'),
    url(r'^update/(?P<id>[0-9]+)/$', views.update_task, name='update_task'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_task, name='delete_task'),
    url(r'^delete_archived/(?P<id>[0-9]+)/$', views.delete_archived_task, name='delete_archived_task'),
    url(r'^assigned/$', views.assigned_tasks, name='assigned_tasks'),
    url(r'^can_read/$', views.can_read_tasks, name='can_read_tasks'),
    url(r'^can_write/$', views.can_write_tasks, name='can_write_tasks'),
    url(r'^category/(?P<id>[0-9]+)/$', views.tasks_by_category, name='tasks_by_category'),
    url(r'^status/(?P<id>[0-9]+)/$', views.tasks_by_status, name='tasks_by_status'),
    url(r'^priority/(?P<id>[0-9]+)/$', views.tasks_by_priority, name='tasks_by_priority'),
    url(r'^plan/(?P<id>[0-9]+)/$', views.tasks_by_plan, name='tasks_by_plan'),
]

notifications_patterns = [
    url(r'^$', views.notifications, name='notifications'),
    url(r'^new/(?P<id>[0-9]+)/$', views.create_notification, name='add_notification'),
    url(r'^all/$', views.all_notifications, name='all_notifications'),
    url(r'^created/$', views.created_notifications, name='created_notifications'),
    url(r'^pending/$', views.pending_notifications, name='pending_notifications'),
    url(r'^shown/$', views.shown_notifications, name='shown_notifications'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_notification, name='edit_notification'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_notification, name='delete_notification'),
    url(r'^set_as_shown/(?P<id>[0-9]+)/$', views.set_notification_as_shown, name='set_notification_as_shown'),
]

plans_patterns = [
    url(r'^templates/$', views.templates, name='templates'),
    url(r'^templates/new$', views.create_template_task, name='new_template'),
    url(r'^$', views.plans, name='plans'),
    url(r'^new/$', views.create_plan, name='new_plan'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_plan, name='edit_plan'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_plan, name='delete_plan'),
]

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^users/', include(users_patterns)),
    url(r'^categories/', include(categories_patterns)),
    url(r'^tasks/', include(tasks_patterns)),
    url(r'^notifications/', include(notifications_patterns)),
    url(r'^plans/', include(plans_patterns))
]

task-manager/web/web/urls.py
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('task_manager.urls')),
]

task-manager/web/templates/tasks/edit.html
{% extends 'base.html' %}

{% block title %}Edit task{% endblock %}

{% block content %}
{% load bootstrap4 %}
{{ form.media }}

<h2>Edit task</h2>
<div class='form' style="position: relative">
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-success">Update</button>
    {% endbuttons %}
  </form>
</div>
<input class='btn btn-primary' type=button value="Back" onClick="javascript:history.go(-1);">
{% endblock %}

task-manager/web/templates/tasks/index.html
{% extends 'base.html' %}
{% block title %}Tasks{% endblock %}
{% block content %}
{% load task_tags %}
{% load fontawesome %}
<h2>{{header|safe}} {% fontawesome_icon 'thumb-tack' color='red' %}</h2>
<div class='table-responsive' id='table'>
  <table class="table table-hover" style="width: inherit;">
    <div class="input-group col-md-3" style='padding-left: 0'>
      <input class="form-control search" placeholder="Search...">
      <span class="input-group-append">
        <button class="btn btn-outline-secondary" type="button">
          <i class="fa fa-search"></i>
        </button>
      </span>
    </div>
    <thead>
      <tr>
        <th class="sort" data-sort="id">ID</th>
        <th class="sort" data-sort="title">Title</th>
        <th class="sort" data-sort="note">Note</th>
        <th class="sort" data-sort="category">Category</th>
        <th class="sort" data-sort="status">Status</th>
        <th class="sort" data-sort="priority">Priority</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody class="list">
      {% for task in tasks %}
      <tr>
        <td class="id" data-toggle="modal" data-id="{{task.id}}" data-title="{{task.title}}" data-target="#modal" data-status="{{task.status}}" data-priority="{{task.priority}}" scope="row">{{task.id}}</td>
        <td class="title" data-toggle="modal" data-id="{{task.id}}" data-title="{{task.title}}" data-target="#modal" data-status="{{task.status}}" data-priority="{{task.priority}}">{{task.title}}</td>
        <td class="note" data-toggle="modal" data-id="{{task.id}}" data-title="{{task.title}}" data-target="#modal" data-status="{{task.status}}" data-priority="{{task.priority}}">{{task.note}}</td>
        <td class="category">
          {% if foreign_category %}
          {% get_category_name_by_id user.id task.category_id %}
          {% else %}
          <a href="{% url 'task_manager:tasks_by_category' task.category_id %}">{% get_category_name_by_id user.id task.category_id %}</a>
          {% endif %}
        </td>
        <td class="status" value={{task.status}}>
          <h5><a class="badge badge-{% get_status_badge_class task.status %}" href="{% url 'task_manager:tasks_by_status' task.status %}">{% get_status task.status %}</a></h5>
        </td>
        <td class="priority" value={{task.priority}}>
          <h5><a class="badge badge-{% get_priority_badge_class task.priority %}" href="{% url 'task_manager:tasks_by_priority' task.priority %}">{% get_priority task.priority %}</a></h5>
        </td>
        <td>
          <a href="{% url 'task_manager:show_task' task.id %}" class='btn btn-info'>Show</a>
          {% if view != 'can_read' %}
            <a href="{% url 'task_manager:edit_task' task.id %}" class='btn btn-warning'>Edit</a>
            {% if task.status != 3 %}
              <form style='display: inline-block;' action="{% url 'task_manager:delete_task' task.id %}" method='post'>
                {% csrf_token %}
                <button type='submit' class='btn btn-danger' onclick="return confirm('Are you sure you want to delete this task?')">Delete</button>
              </form>
            {% else %}
              <form style='display: inline-block;' action="{% url 'task_manager:delete_archived_task' task.id %}" method='post'>
                {% csrf_token %}
                <button type='submit' class='btn btn-danger' onclick="return confirm('Are you sure you want to delete this task?')">Delete</button>
              </form>
            {% endif %}
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <ul class='pagination'></ul>
</div>
<a href="{% url 'task_manager:new_task' %}{{query}}" class='btn btn-primary'>Add task</a>
{% if view != 'can_read' and status_id != '3' %}
<!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="title">Modal title</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h5>Set status:</h5>
        <div class="set-status">
          <button class='btn btn-outline-secondary' data-value="0">TODO</button>
          <button class='btn btn-outline-info' data-value="1">IN PROGRESS</button>
          <button class='btn btn-outline-success' data-value="2">DONE</button>
        </div>
        <hr>
        <h5>Set priority:</h5>
        <div class='set-priority'>
          <button class="btn btn-outline-secondary" data-value="0">MIN</button>
          <button class="btn btn-outline-info" data-value="1">LOW</button>
          <button class="btn btn-outline-primary" data-value="2">MEDIUM</button>
          <button class="btn btn-outline-warning" data-value="3">HIGH</button>
          <button class="btn btn-outline-danger" data-value="4">MAX</button>
        </div>
        <hr>
        <h5>Actions:</h5>
        <a href="{% url 'task_manager:new_task' %}?parent_task_id=" class="btn btn-primary" id="add-parent">Add inner task</a>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form id='update-form' method="post">
          {% csrf_token %}
          <input type="hidden" id="status" name="status" value="">
          <input type="hidden" id="priority" name="priority" value="">
          <button type="submit" class="btn btn-primary">Save changes</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %}
<script>
var options = {
  valueNames: [ 'id', 'title', 'note', 'category', {
    name: 'status',
    attr: 'value'
  }, {
    name: 'priority',
    attr: 'value'
  }],
  pagination: true,
  page: 7,
};
var list = new List('table', options);
if(list.size() / list.page <= 1){
  document.getElementsByClassName('pagination')[0].style.display = 'none';
}
{% if view != 'can_read' and status_id != '3' %}
$('#modal').on('show.bs.modal', function (event) {
  var row = $(event.relatedTarget)
  var id = row.data('id')
  var title = row.data('title')
  var status = row.data('status')
  var priority = row.data('priority')
  var modal = $(this)
  modal.find('.modal-title').text(title)
  modal.find('#add-parent').attr('href', "{% url 'task_manager:new_task' %}?parent_task_id=" + id)
  modal.find('#update-form').attr('action', '/tasks/update/' + id + '/')

  $('.set-status button').siblings().removeClass('active')
  $('.set-priority button').siblings().removeClass('active')
  $(`.set-status button[data-value='${status}']`).addClass('active')
  $(`.set-priority button[data-value='${priority}']`).addClass('active')
  $('#status').attr('value', status)
  $('#priority').attr('value', priority)
})
$('.set-status button').click(function() {
  $(this).addClass('active').siblings().removeClass('active');
  $('#status').attr('value', $(this).data('value'))
});
$('.set-priority button').click(function() {
  $(this).addClass('active').siblings().removeClass('active');
  $('#priority').attr('value', $(this).data('value'))
});
{% endif %}
</script>
{% endblock %}

task-manager/web/templates/tasks/new.html
{% extends 'base.html' %}

{% block title %}New task{% endblock %}

{% block content %}
{% load bootstrap4 %}
{{ form.media }}
<h2>New task</h2>
<div class='form' style="position: relative">
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-success">Submit</button>
    {% endbuttons %}
  </form>
</div>
<input class='btn btn-primary' type=button value="Back" onClick="javascript:history.go(-1);">
{% endblock %}

task-manager/web/templates/tasks/show.html
{% extends 'base.html' %}

{% block title %}Task info{% endblock %}
{% load task_tags %}
{% block content %}
<h2>Task info</h2>
<table class="table table-striped">
  <tbody>
    <tr>
      <td class="title">ID</td>
      <td>{{task.id}}</td>
    </tr>
    <tr>
      <td class="title">Title</td>
      <td>{{task.title}}</td>
    </tr>
    <tr>
      <td class="title">Note</td>
      <td>{{task.note}}</td>
    </tr>
    <tr>
      <td class="title">Category</td>
      <td>
        {% if foreign_category %}
        {{category.name}}
        {% else %}
        <a href="{% url 'task_manager:tasks_by_category' category.id %}"> {{category.name}}</a>
        {% endif %}
      </td>
    </tr>
    <tr>
      <td class="title">Priority</td>
      <td>
        <h5><a class="badge badge-{% get_priority_badge_class task.priority %}" href="{% url 'task_manager:tasks_by_priority' task.priority %}"> {{priority}}</a></h5>
      </td>
    </tr>
    <tr>
      <td class="title">Status</td>
      <td>
        <h5><a class="badge badge-{% get_status_badge_class task.status %}" href="{% url 'task_manager:tasks_by_status' task.status %}"> {{status}}</a></h5>
      </td>
    </tr>
    <tr>
      <td class="title">Created at</td>
      <td>{{task.created_at}}</td>
    </tr>
    <tr>
      <td class="title">Updated at</td>
      <td>{{task.updated_at}}</td>
    </tr>
    <tr>
      <td class="title">Event</td>
      <td>{{task.is_event}}</td>
    </tr>
    <tr>
      <td class="title">Start time</td>
      <td>{{task.start_time}}</td>
    </tr>
    <tr>
      <td class="title">End time</td>
      <td>{{task.end_time}}</td>
    </tr>
    <tr>
      <td class="title">Parent task</td>
      <td>
        {% if parent_task_title is not None %}
        <a href="{% url 'task_manager:show_task' task.parent_task_id%}">{{ parent_task_title }}</a>
        {% else %}
        {{ parent_task_title }}
        {% endif %}
      </td>
    </tr>
    <tr>
      <td class="title">Assigned user</td>
      <td>{{assigned_user}}</td>
    </tr>
    <tr>
      <td class="title">Inner tasks</td>
      <td>
        {% for inner_task in inner_tasks %}
          <a href="{% url 'task_manager:show_task' inner_task.id%}">{{ inner_task.title }}</a>{% if not forloop.last %},{% endif %}
        {% endfor %}
      </td>
    </tr>
    <tr>
      <td class="title">Creator</td>
      <td>{{creator}}</td>
    </tr>
  </tbody>
</table>
<input class='btn btn-primary' type=button value="Back" onClick="javascript:history.go(-1);">
<div class='right'>
  <a href="{% url 'task_manager:edit_task' task.id %}" class='btn btn-warning'>Edit</a>
  <form style='display: inline-block;' action="{% url 'task_manager:delete_task' task.id %}" method='post'>
    {% csrf_token %}
    <button type='submit' class='btn btn-danger' onclick="return confirm('Are you sure you want to delete this task?')">Delete</button>
  </form>
</div>
{% endblock %}