task-manager/web/task_manager/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from . import views

app_name = "task_manager"

users_patterns = [
    url(r'^$', views.users, name='users'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'task_manager:home'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
]

categories_patterns = [
    url(r'^$', views.categories, name='categories'),
    url(r'^new/$', views.create_category, name='new_category'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_category, name='edit_category'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_category, name='delete_category'),
]

tasks_patterns = [
    url(r'^$', views.tasks, name='tasks'),
    url(r'^new/$', views.create_task, name='new_task'),
    url(r'^(?P<id>[0-9]+)/$', views.show_task, name='show_task'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_task, name='edit_task'),
    url(r'^update/(?P<id>[0-9]+)/$', views.update_task, name='update_task'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_task, name='delete_task'),
    url(r'^delete_archived/(?P<id>[0-9]+)/$', views.delete_archived_task, name='delete_archived_task'),
    url(r'^assigned/$', views.assigned_tasks, name='assigned_tasks'),
    url(r'^can_read/$', views.can_read_tasks, name='can_read_tasks'),
    url(r'^can_write/$', views.can_write_tasks, name='can_write_tasks'),
    url(r'^category/(?P<id>[0-9]+)/$', views.tasks_by_category, name='tasks_by_category'),
    url(r'^status/(?P<id>[0-9]+)/$', views.tasks_by_status, name='tasks_by_status'),
    url(r'^priority/(?P<id>[0-9]+)/$', views.tasks_by_priority, name='tasks_by_priority'),
    url(r'^plan/(?P<id>[0-9]+)/$', views.tasks_by_plan, name='tasks_by_plan'),
]

notifications_patterns = [
    url(r'^$', views.notifications, name='notifications'),
    url(r'^new/(?P<id>[0-9]+)/$', views.create_notification, name='add_notification'),
    url(r'^all/$', views.all_notifications, name='all_notifications'),
    url(r'^created/$', views.created_notifications, name='created_notifications'),
    url(r'^pending/$', views.pending_notifications, name='pending_notifications'),
    url(r'^shown/$', views.shown_notifications, name='shown_notifications'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_notification, name='edit_notification'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_notification, name='delete_notification'),
    url(r'^set_as_shown/(?P<id>[0-9]+)/$', views.set_notification_as_shown, name='set_notification_as_shown'),
]

plans_patterns = [
    url(r'^templates/$', views.templates, name='templates'),
    url(r'^templates/new$', views.create_template_task, name='new_template'),
    url(r'^$', views.plans, name='plans'),
    url(r'^new/$', views.create_plan, name='new_plan'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_plan, name='edit_plan'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_plan, name='delete_plan'),
]

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^users/', include(users_patterns)),
    url(r'^categories/', include(categories_patterns)),
    url(r'^tasks/', include(tasks_patterns)),
    url(r'^notifications/', include(notifications_patterns)),
    url(r'^plans/', include(plans_patterns))
]

task-manager/web/web/urls.py
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('task_manager.urls')),
]

task-manager/web/templates/notifications/edit.html
{% extends 'base.html' %}

{% block title %}Edit notification{% endblock %}

{% block content %}
{% load bootstrap4 %}

<h2>Edit notification</h2>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-success">Update</button>
  {% endbuttons %}
</form>
<input class='btn btn-primary' type=button value="Back" onClick="javascript:history.go(-1);">
{% endblock %}

task-manager/web/templates/notifications/index.html
{% extends 'base.html' %}
{% block title %}Notifications{% endblock %}

{% block content %}
{% load notification_tags %}
{% load fontawesome %}
<h2>{{header}} {% fontawesome_icon 'bell-o' color='red' %}</h2>
<div class='table-responsive' id='table'>
  <div class="input-group col-md-3" style='padding-left: 0'>
    <input class="form-control search" placeholder="Search...">
    <span class="input-group-append">
      <button class="btn btn-outline-secondary" type="button">
        <i class="fa fa-search"></i>
      </button>
    </span>
  </div>
  <table class="table table-hover" style="width: inherit;">
    <thead>
      <tr>
        <th class="sort" data-sort="id">ID</th>
        <th class="sort" data-sort="title">Title</th>
        <th class="sort" data-sort="relative_start_time">Relative start time</th>
        <th class="sort" data-sort="status">Status</th>
        <th class="sort" data-sort="task">Task</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody class="list">
      {% for notification in notifications %}
      <tr>
        <td class="id" scope="row">{{notification.id}}</td>
        <td class="title">{{notification.title}}</td>
        <td class="relative_start_time">{% get_timedelta notification.relative_start_time %}</td>
        <td class="status" value={{notification.status}}>
          <h5><span class="badge badge-{% get_status_badge_class notification.status %}">{% get_status notification.status %}</span></h5>
        </td>
        <td class="task">
          <a href="{% url 'task_manager:show_task' notification.task_id %}">
            {% get_task_title_by_id notification.user_id notification.task_id %}
          </a>
        </td>
        <td>
          {% if view == 'pending' %}
          <form style='display: inline-block;' action="{% url 'task_manager:set_notification_as_shown' notification.id %}" method='post'>
            {% csrf_token %}
            <button type='submit' class='btn btn-primary'>Set as shown</button>
          </form>
          {% endif %}
          <a href="{% url 'task_manager:edit_notification' notification.id %}" class='btn btn-warning'>Edit</a>
          <form style='display: inline-block;' action="{% url 'task_manager:delete_notification' notification.id %}" method='post'>
            {% csrf_token %}
            <button type='submit' class='btn btn-danger' onclick="return confirm('Are you sure you want to delete this notification?')">Delete</button>
          </form>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <ul class='pagination'></ul>
</div>
<script>
var options = {
  valueNames: [ 'id', 'title', 'relative_start_time', {
    name: 'status',
    attr: 'value'
  }, 'task' ],
  pagination: true,
  page: 7,
};
var list = new List('table', options);
if(list.size() / list.page <= 1){
  document.getElementsByClassName('pagination')[0].style.display = 'none';
}
</script>
{% endblock %}

task-manager/web/templates/notifications/new.html
{% extends 'base.html' %}

{% block title %}New notification{% endblock %}

{% block content %}
{% load bootstrap4 %}
<h2>New notification</h2>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-success">Submit</button>
  {% endbuttons %}
</form>
<input class='btn btn-primary' type=button value="Back" onClick="javascript:history.go(-1);">
{% endblock %}

task-manager/web/templates/notifications/tasks.html
{% extends 'base.html' %}
{% block title %}Notifications{% endblock %}

{% block content %}
{% load task_tags %}
<h2>Tasks that can have notifications</h2>
<div class='table-responsive' id='table'>
  <div class="input-group col-md-3" style='padding-left: 0'>
    <input class="form-control search" placeholder="Search...">
    <span class="input-group-append">
      <button class="btn btn-outline-secondary" type="button">
        <i class="fa fa-search"></i>
      </button>
    </span>
  </div>
  <table class="table table-hover" style="width: inherit;">
    <thead>
      <tr>
        <th class="sort" data-sort="id">ID</th>
        <th class="sort" data-sort="title">Title</th>
        <th class="sort" data-sort="note">Note</th>
        <th class="sort" data-sort="category">Category</th>
        <th class="sort" data-sort="status">Status</th>
        <th class="sort" data-sort="priority">Priority</th>
        <th class="sort" data-sort="start_time">Start time</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody class="list">
      {% for task in tasks %}
      <tr>
        <td class="id" scope="row">{{task.id}}</td>
        <td class="title">{{task.title}}</td>
        <td class="note">{{task.note}}</td>
        <td class="category">{% get_category_name_by_id user_id task.category_id %}</td>
        <td class="status" value={{task.status}}>
          <h5><a class="badge badge-{% get_status_badge_class task.status %}" href="{% url 'task_manager:tasks_by_status' task.status %}">{% get_status task.status %}</a></h5>
        </td>
        <td class="priority" value={{task.priority}}>
          <h5><a class="badge badge-{% get_priority_badge_class task.priority %}" href="{% url 'task_manager:tasks_by_priority' task.priority %}">{% get_priority task.priority %}</a></h5>
        </td>
        <td class="start_time">{{task.start_time}}</td>
        <td>
          <a href="{% url 'task_manager:edit_task' task.id %}" class='btn btn-warning'>Edit task</a>
          <a href="{% url 'task_manager:add_notification' task.id %}" class='btn btn-primary'>Add notification</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
<script>
var options = {
  valueNames: [ 'id', 'title', 'note', 'category', {
    name: 'status',
    attr: 'value'
  }, {
    name: 'priority',
    attr: 'value'
  }],
  pagination: true,
  page: 7,
};
var list = new List('table', options);
if(list.size() / list.page <= 1){
  document.getElementsByClassName('pagination')[0].style.display = 'none';
}
</script>
{% endblock %}