task-manager/web/task_manager/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from . import views

app_name = "task_manager"

users_patterns = [
    url(r'^$', views.users, name='users'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'task_manager:home'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
]

categories_patterns = [
    url(r'^$', views.categories, name='categories'),
    url(r'^new/$', views.create_category, name='new_category'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_category, name='edit_category'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_category, name='delete_category'),
]

tasks_patterns = [
    url(r'^$', views.tasks, name='tasks'),
    url(r'^new/$', views.create_task, name='new_task'),
    url(r'^(?P<id>[0-9]+)/$', views.show_task, name='show_task'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_task, name='edit_task'),
    url(r'^update/(?P<id>[0-9]+)/$', views.update_task, name='update_task'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_task, name='delete_task'),
    url(r'^delete_archived/(?P<id>[0-9]+)/$', views.delete_archived_task, name='delete_archived_task'),
    url(r'^assigned/$', views.assigned_tasks, name='assigned_tasks'),
    url(r'^can_read/$', views.can_read_tasks, name='can_read_tasks'),
    url(r'^can_write/$', views.can_write_tasks, name='can_write_tasks'),
    url(r'^category/(?P<id>[0-9]+)/$', views.tasks_by_category, name='tasks_by_category'),
    url(r'^status/(?P<id>[0-9]+)/$', views.tasks_by_status, name='tasks_by_status'),
    url(r'^priority/(?P<id>[0-9]+)/$', views.tasks_by_priority, name='tasks_by_priority'),
    url(r'^plan/(?P<id>[0-9]+)/$', views.tasks_by_plan, name='tasks_by_plan'),
]

notifications_patterns = [
    url(r'^$', views.notifications, name='notifications'),
    url(r'^new/(?P<id>[0-9]+)/$', views.create_notification, name='add_notification'),
    url(r'^all/$', views.all_notifications, name='all_notifications'),
    url(r'^created/$', views.created_notifications, name='created_notifications'),
    url(r'^pending/$', views.pending_notifications, name='pending_notifications'),
    url(r'^shown/$', views.shown_notifications, name='shown_notifications'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_notification, name='edit_notification'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_notification, name='delete_notification'),
    url(r'^set_as_shown/(?P<id>[0-9]+)/$', views.set_notification_as_shown, name='set_notification_as_shown'),
]

plans_patterns = [
    url(r'^templates/$', views.templates, name='templates'),
    url(r'^templates/new$', views.create_template_task, name='new_template'),
    url(r'^$', views.plans, name='plans'),
    url(r'^new/$', views.create_plan, name='new_plan'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_plan, name='edit_plan'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_plan, name='delete_plan'),
]

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^users/', include(users_patterns)),
    url(r'^categories/', include(categories_patterns)),
    url(r'^tasks/', include(tasks_patterns)),
    url(r'^notifications/', include(notifications_patterns)),
    url(r'^plans/', include(plans_patterns))
]

task-manager/web/web/urls.py
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('task_manager.urls')),
]

task-manager/web/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Base view{% endblock %}</title>
  {% load static %}
  {% load fontawesome %}
  <script src="{% static "js/jquery.min.js" %}"></script>
  <script src="{% static "js/popper.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/moment.min.js" %}"></script>
  <script src="{% static "js/tempusdominus.min.js" %}"></script>
  <script src="{% static "js/list.min.js" %}"></script>
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  {% fontawesome_stylesheet %}
  <link rel="stylesheet" href="{% static "css/tempusdominus.css" %}">
  <link rel="stylesheet" href="{% static "css/style.css" %}">
  {{ form.media }}

</head>
<body>
	{% include "header.html" %}
	<main>
		<div class='container'>
		    {% block content %}
		    {% endblock %}
		</div>
	</main>
</body>
</html>

task-manager/web/templates/header.html
{% block header %}
{% load fontawesome %}
{% load notification_tags %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Task Manager</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if nav_bar == 'categories' %}active{% endif %}" href='{% url 'task_manager:categories' %}'>{% fontawesome_icon 'star' %} Categories<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle {% if nav_bar == 'tasks' %}active{% endif %}" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% fontawesome_icon 'tasks' %} Tasks</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href='{% url 'task_manager:tasks' %}'>My</a>
            <a class="dropdown-item" href='{% url 'task_manager:assigned_tasks' %}'>Assigned</a>
            <a class="dropdown-item" href='{% url 'task_manager:can_read_tasks' %}'>Can read</a>
            <a class="dropdown-item" href='{% url 'task_manager:can_write_tasks' %}'>Can write</a>
            <a class="dropdown-item" href='{% url 'task_manager:tasks_by_status' 3 %}'>Archived</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle {% if nav_bar == 'notifications' %}active{% endif %}" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% fontawesome_icon 'exclamation' %} Notifications</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href='{% url 'task_manager:notifications' %}'>Tasks</a>
            <a class="dropdown-item" href='{% url 'task_manager:all_notifications' %}'>All</a>
            <a class="dropdown-item" href='{% url 'task_manager:created_notifications' %}'>Created</a>
            <a class="dropdown-item" href='{% url 'task_manager:pending_notifications' %}'>Pending</a>
            <a class="dropdown-item" href='{% url 'task_manager:shown_notifications' %}'>Shown</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if nav_bar == 'plans' %}active{% endif %}" href="{% url 'task_manager:plans' %}">{% fontawesome_icon 'paperclip' %} Task plans</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if nav_bar == 'users' %}active{% endif %}" href='{% url 'task_manager:users' %}'>{% fontawesome_icon 'users' %} Users<span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <ul class="navbar-nav mr-auto"></ul>
      {% if user.is_authenticated %}
        <ul class="navbar-nav ">
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navDropDownLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% fontawesome_icon 'bell' %}</a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navDropDownLink">
              {% for notification in pending_notifications %}
                <div class="dropdown-item background-gray">
                  <div class='notifications'>
                    <div class='notification'>
                      <div class='title inline'>
                        <h5>{{notification.title}}</h5>
                      </div>
                      <div class='task inline margin-right'>
                        <a href="{% url 'task_manager:show_task' notification.task_id %}">
                          <h5>{% get_task_title_by_id notification.user_id notification.task_id %}</h5>
                        </a>
                      </div>
                      <form style='display: inline-block;' action="{% url 'task_manager:set_notification_as_shown' notification.id %}" method='post'>
                        {% csrf_token %}
                        <button type='submit' class='btn btn-primary'>Set as shown</button>
                      </form>
                    </div>
                  </div>
                </div>
                {% if not forloop.last %}
                <div class="dropdown-divider"></div>
                {% endif %}
              {% endfor %}
              {% if not pending_notifications %}
                <div class="dropdown-item">
                    <h5>No notifications</h5>
                </div> 
              {% endif %}
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ">
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navDropDownLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Profile</a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navDropDownLink">
              <div class="dropdown-item">{{user.username}}</div>
              <div class="dropdown-item">Experience: {{user.level.experience}}</div>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href='{% url 'task_manager:logout' %}'>Logout</a>
            </div>
          </li>
        </ul>
      {% else %}
        <a href='{% url 'task_manager:login' %}' class='btn btn-light mr-2'>Login</a>
        <a href='{% url 'task_manager:signup' %}' class='btn btn-outline-success'>Signup</a>
      {% endif %}
    </div>
  </nav>
{% endblock %}

task-manager/web/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <div class='jumbotron'>
  	<h1 class='display-1'>Hello, {{ username }} 👋</h1>
    <div class='display-4'>
      It's time to complete <a href='{% url 'task_manager:tasks' %}'>your tasks</a>!
    </div>
  </div>
{% endblock %}