task-manager/web/task_manager/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from . import views

app_name = "task_manager"

users_patterns = [
    url(r'^$', views.users, name='users'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'task_manager:home'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
]

categories_patterns = [
    url(r'^$', views.categories, name='categories'),
    url(r'^new/$', views.create_category, name='new_category'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_category, name='edit_category'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_category, name='delete_category'),
]

tasks_patterns = [
    url(r'^$', views.tasks, name='tasks'),
    url(r'^new/$', views.create_task, name='new_task'),
    url(r'^(?P<id>[0-9]+)/$', views.show_task, name='show_task'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_task, name='edit_task'),
    url(r'^update/(?P<id>[0-9]+)/$', views.update_task, name='update_task'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_task, name='delete_task'),
    url(r'^delete_archived/(?P<id>[0-9]+)/$', views.delete_archived_task, name='delete_archived_task'),
    url(r'^assigned/$', views.assigned_tasks, name='assigned_tasks'),
    url(r'^can_read/$', views.can_read_tasks, name='can_read_tasks'),
    url(r'^can_write/$', views.can_write_tasks, name='can_write_tasks'),
    url(r'^category/(?P<id>[0-9]+)/$', views.tasks_by_category, name='tasks_by_category'),
    url(r'^status/(?P<id>[0-9]+)/$', views.tasks_by_status, name='tasks_by_status'),
    url(r'^priority/(?P<id>[0-9]+)/$', views.tasks_by_priority, name='tasks_by_priority'),
    url(r'^plan/(?P<id>[0-9]+)/$', views.tasks_by_plan, name='tasks_by_plan'),
]

notifications_patterns = [
    url(r'^$', views.notifications, name='notifications'),
    url(r'^new/(?P<id>[0-9]+)/$', views.create_notification, name='add_notification'),
    url(r'^all/$', views.all_notifications, name='all_notifications'),
    url(r'^created/$', views.created_notifications, name='created_notifications'),
    url(r'^pending/$', views.pending_notifications, name='pending_notifications'),
    url(r'^shown/$', views.shown_notifications, name='shown_notifications'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_notification, name='edit_notification'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_notification, name='delete_notification'),
    url(r'^set_as_shown/(?P<id>[0-9]+)/$', views.set_notification_as_shown, name='set_notification_as_shown'),
]

plans_patterns = [
    url(r'^templates/$', views.templates, name='templates'),
    url(r'^templates/new$', views.create_template_task, name='new_template'),
    url(r'^$', views.plans, name='plans'),
    url(r'^new/$', views.create_plan, name='new_plan'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit_plan, name='edit_plan'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete_plan, name='delete_plan'),
]

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^users/', include(users_patterns)),
    url(r'^categories/', include(categories_patterns)),
    url(r'^tasks/', include(tasks_patterns)),
    url(r'^notifications/', include(notifications_patterns)),
    url(r'^plans/', include(plans_patterns))
]

task-manager/web/web/urls.py
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('task_manager.urls')),
]

task-manager/web/templates/plans/edit.html
{% extends 'base.html' %}

{% block title %}Edit plan{% endblock %}

{% block content %}
{% load bootstrap4 %}
{{ form.media }}

<h2>Edit plan</h2>
<div class='form' style="position: relative">
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-success">Update</button>
    {% endbuttons %}
  </form>
</div>
<input class='btn btn-primary' type=button value="Back" onClick="javascript:history.go(-1);">
{% endblock %}

task-manager/web/templates/plans/index.html
{% extends 'base.html' %}
{% block title %}Plans{% endblock %}

{% block content %}
{% load notification_tags %}
{% load fontawesome %}
<h2>Plans {% fontawesome_icon 'paperclip' color='orange' %}</h2>
<div class='table-responsive' id='table'>
  <div class="input-group col-md-3" style='padding-left: 0'>
    <input class="form-control search" placeholder="Search...">
    <span class="input-group-append">
      <button class="btn btn-outline-secondary" type="button">
        <i class="fa fa-search"></i>
      </button>
    </span>
  </div>
  <table class="table table-hover" style="width: inherit;">
    <thead>
      <tr>
        <th class="sort" data-sort="id">ID</th>
        <th class="sort" data-sort="interval">Interval</th>
        <th class="sort" data-sort="last_created_at">Last created at</th>
        <th class="sort" data-sort="task">Task</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody class="list">
      {% for plan in plans %}
      <tr>
        <td class="id" scope="row">{{plan.id}}</td>
        <td class="interval">{% get_timedelta plan.interval %}</td>
        <td class="last_created_at">{{plan.last_created_at}}</td>
        <td class="task">
          <a href="{% url 'task_manager:show_task' plan.task_id %}">
            {% get_task_title_by_id plan.user_id plan.task_id %}
          </a>
        </td>
        <td>
          <a href="{% url 'task_manager:tasks_by_plan' plan.id %}" class='btn btn-info'>Created tasks</a>
          <a href="{% url 'task_manager:edit_plan' plan.id %}" class='btn btn-warning'>Edit</a>
          <form style='display: inline-block;' action="{% url 'task_manager:delete_plan' plan.id %}" method='post'>
            {% csrf_token %}
            <button type='submit' class='btn btn-danger' onclick="return confirm('Are you sure you want to delete this plan?')">Delete</button>
          </form>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <ul class='pagination'></ul>
</div>
<a href="{% url 'task_manager:new_plan' %}" class='btn btn-primary'>Add plan</a>
<a href="{% url 'task_manager:templates' %}" class='btn btn-info'>Manage task templates</a>
<script>
var options = {
  valueNames: [ 'id', 'interval', 'last_created_at', 'task' ],
  pagination: true,
  page: 7,
};
var list = new List('table', options);
if(list.size() / list.page <= 1){
  document.getElementsByClassName('pagination')[0].style.display = 'none';
}
</script>
{% endblock %}

task-manager/web/templates/plans/new.html
{% extends 'base.html' %}

{% block title %}New plan{% endblock %}

{% block content %}
{% load bootstrap4 %}
{{ form.media }}

<h2>New plan</h2>
<a href="{% url 'task_manager:new_template' %}" class='btn btn-warning'>Add task template</a>
<div class='form' style="position: relative; margin-top: 20px">
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-success">Submit</button>
    {% endbuttons %}
  </form>
</div>
<input class='btn btn-primary' type=button value="Back" onClick="javascript:history.go(-1);">
{% endblock %}

task-manager/web/templates/plans/templates.html
{% extends 'base.html' %}
{% block title %}Templates{% endblock %}

{% block content %}
{% load task_tags %}
<h2>Task templates</h2>
<div class='table-responsive' id='table'>
  <div class="input-group col-md-3" style='padding-left: 0'>
    <input class="form-control search" placeholder="Search...">
    <span class="input-group-append">
      <button class="btn btn-outline-secondary" type="button">
        <i class="fa fa-search"></i>
      </button>
    </span>
  </div>
  <table class="table table-hover" style="width: inherit;">
    <thead>
      <tr>
        <th class="sort" data-sort="id">ID</th>
        <th class="sort" data-sort="title">Title</th>
        <th class="sort" data-sort="note">Note</th>
        <th class="sort" data-sort="category">Category</th>
        <th class="sort" data-sort="status">Status</th>
        <th class="sort" data-sort="priority">Priority</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody class="list">
      {% for task in tasks %}
      <tr>
        <td class="id" scope="row">{{task.id}}</td>
        <td class="title">{{task.title}}</td>
        <td class="note">{{task.note}}</td>
        <td class="category"><a href="{% url 'task_manager:tasks_by_category' task.category_id %}">{% get_category_name_by_id user.id task.category_id %}</a></td>
        <td class="status" value={{task.status}}>
          <h5><a class="badge badge-{% get_status_badge_class task.status %}" href="{% url 'task_manager:tasks_by_status' task.status %}">{% get_status task.status %}</a></h5>
        </td>
        <td class="priority" value={{task.priority}}>
          <h5><a class="badge badge-{% get_priority_badge_class task.priority %}" href="{% url 'task_manager:tasks_by_priority' task.priority %}">{% get_priority task.priority %}</a></h5>
        </td>
        <td>
          <a href="{% url 'task_manager:new_plan'%}?task_template={{task.id}}" class='btn btn-success'>Add plan</a>
          <a href="{% url 'task_manager:show_task' task.id %}" class='btn btn-primary'>Show</a>
          <a href="{% url 'task_manager:edit_task' task.id %}" class='btn btn-warning'>Edit</a>
          <form style='display: inline-block;' action="{% url 'task_manager:delete_task' task.id %}" method='post'>
            {% csrf_token %}
            <button type='submit' class='btn btn-danger' onclick="return confirm('Are you sure you want to delete this task?')">Delete</button>
          </form>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <ul class='pagination'></ul>
</div>
<a href="{% url 'task_manager:new_template' %}" class='btn btn-primary'>Add template task</a>
<script>
var options = {
  valueNames: [ 'id', 'title', 'note', 'category', {
    name: 'status',
    attr: 'value'
  }, {
    name: 'priority',
    attr: 'value'
  }],
  pagination: true,
  page: 7,
};
var list = new List('table', options);
if(list.size() / list.page <= 1){
  document.getElementsByClassName('pagination')[0].style.display = 'none';
}
</script>
{% endblock %}